sensor/stmemsc: Align stmemsc i/f to v2.00
zephyrproject-rtos/hal_st pull request #7
Opened 2021-06-14 13:58 UTC by avisconti

Align stmemsc HAL i/f to v2.00

2021-06-14 14:04 UTC, erwango requested changes
Can you add a matching PR that would allow to build changes in main branch ?

2021-06-14 16:38 UTC, avisconti commented
> Can you add a matching PR that would allow to build changes in main branch ?

I'm adding in main branch a PR that is changing the west.yaml file with a reference to this PR.

2021-06-15 13:51 UTC, MaureenHelm approved these changes

2021-06-15 13:57 UTC, erwango approved these changes

2021-06-15 14:21 UTC, merged